Support for `msg` arg to `cancel()` added in Python 3.9
achimnol/aiotools pull request #32
Opened 2022-02-12 20:21 UTC by bdowning

Python 3.9 added a `msg` arg to `cancel()`.  If the patched parent task of a task group is cancelled with this argument, we get this error:

```
TypeError: _task_cancel() takes 2 positional arguments but 3 were given
```

This adds a test for this scenario, and then fixes it by adding an optional argument to the wrapper.

2022-02-16 15:49 UTC, achimnol commented
> @achimnol Pinging about this. The tests haven't been run due to needing authorization but I suspect they'll "fail" based on the head of `main` failing at the moment. Just bad timing on my part not getting in earlier. :)
> 
> Would there be any way to get this into a release soon? We're seeing this issue in our code that's attempting to use `TaskGroups`. I can probably monkey-patch around it but having a fix upstream would be great.

Oh, I just have been busy. Thanks for your first contribution!

2022-02-16 16:04 UTC, achimnol approved these changes
LGTM!

2022-02-16 16:16 UTC, achimnol commented
Hm... a recent update has broken the test suite. I'll inspect.

2022-02-16 16:18 UTC, bdowning commented
Thanks; I'll check in later and rebase if there's a fix.

2022-02-16 16:22 UTC, achimnol commented
> Thanks; I'll check in later and rebase if there's a fix.

It's fixed now in the main branch. You may rebase or merge it.

2022-02-17 01:16 UTC, bdowning commented
OK, rebased!  Sorry for the wait.

2022-02-17 08:53 UTC, achimnol requested changes
Could you just do the followings to pass CI checks?

* Add `changes/32.feature.md` that contains a single imperative sentence to describe what has changed.
* Remove the unused `t1` variable to fix the flake8 (lint) error.

Thanks!

2022-02-17 13:08 UTC, bdowning commented
Done.

It looks like every time I push it goes back to saying "workflow awaiting approval" and the CI checks don't run.  Since there's also no local scriptage (that I can see anyway) to run equivalent checks to what CI will do this makes it pretty hard to know that things like the above are missing for contributors.  (I'd cobbled together how to get tests to run by looking at the Github Actions files, but that's not ideal.)

2022-02-18 06:21 UTC, achimnol commented
> Done.
> 
> It looks like every time I push it goes back to saying "workflow awaiting approval" and the CI checks don't run. Since there's also no local scriptage (that I can see anyway) to run equivalent checks to what CI will do this makes it pretty hard to know that things like the above are missing for contributors. (I'd cobbled together how to get tests to run by looking at the Github Actions files, but that's not ideal.) I think having one or the other (i.e. either a "push to run CI" model that doesn't have a several-hours cycle time or a "here's a script to run to do all the checks locally" model) would be beneficial.

This is the GitHub's default setting to prevent potential abusing of executing arbitrary codes in the PR.  If your PR is merged once, then it won't ask explicit permission from the next contributions.

2022-02-18 13:21 UTC, bdowning commented
Fair enough.

Pushed a fix for the `create_task` use and Python 3.6.  Hopefully that's the last of it.

2022-02-19 06:03 UTC, achimnol approved these changes

2022-02-19 06:04 UTC, merged

2022-02-19 06:04 UTC, achimnol commented
Thanks for the contribution!